import type { SemanticTokens } from "@blenx-dev/theme";

export interface ThemePreset {
  name: string;
  label: string;
  tokens: Partial<SemanticTokens>;
}

export const presets: ThemePreset[] = [
  {
    name: "default",
    label: "Blenx Default",
    tokens: {},
  },
  {
    name: "zinc-dark",
    label: "Zinc Dark",
    tokens: {
      background: { default: "#09090b", subtle: "#18181b" },
      surface: {
        default: "#09090b",
        raised: "#27272a",
        overlay: "rgba(0,0,0,0.8)",
        floating: "#18181b",
      },
      text: { primary: "#fafafa", secondary: "#a1a1aa", disabled: "#52525b", inverse: "#09090b" },
      border: { default: "#27272a", subtle: "#18181b", strong: "#3f3f46" },
      interactive: {
        primary: "#fafafa",
        primaryFg: "#09090b",
        primaryHover: "#e4e4e7",
        primaryBg: "#27272a",
        secondary: "#3b82f6",
        secondaryFg: "#ffffff",
        secondaryHover: "#2563eb",
        secondaryBg: "#1e3a5f",
        neutral: "#52525b",
        neutralFg: "#fafafa",
      },
    },
  },
  {
    name: "vercel-light",
    label: "Vercel Light",
    tokens: {
      background: { default: "#ffffff", subtle: "#fafafa" },
      surface: {
        default: "#ffffff",
        raised: "#ffffff",
        overlay: "rgba(0,0,0,0.5)",
        floating: "#ffffff",
      },
      text: { primary: "#000000", secondary: "#666666", disabled: "#888888", inverse: "#ffffff" },
      border: { default: "#eaeaea", subtle: "#fafafa", strong: "#888888" },
      interactive: {
        primary: "#000000",
        primaryFg: "#ffffff",
        primaryHover: "#333333",
        primaryBg: "#f5f5f5",
        secondary: "#0070f3",
        secondaryFg: "#ffffff",
        secondaryHover: "#0060df",
        secondaryBg: "#ebf3fe",
        neutral: "#888888",
        neutralFg: "#ffffff",
      },
    },
  },
  {
    name: "linear-dark",
    label: "Linear Dark",
    tokens: {
      background: { default: "#0E0F11", subtle: "#151618" },
      surface: {
        default: "#151618",
        raised: "#2B2D31",
        overlay: "rgba(0,0,0,0.7)",
        floating: "#1F2124",
      },
      text: { primary: "#F2F2F2", secondary: "#8A8F98", disabled: "#4C5058", inverse: "#0E0F11" },
      border: { default: "#2B2D31", subtle: "#1F2124", strong: "#3C3F44" },
      interactive: {
        primary: "#E5E5E5",
        primaryFg: "#0E0F11",
        primaryHover: "#D1D1D1",
        primaryBg: "#2B2D31",
        secondary: "#5E6AD2",
        secondaryFg: "#ffffff",
        secondaryHover: "#4A56C0",
        secondaryBg: "#2D3160",
        neutral: "#4C5058",
        neutralFg: "#F2F2F2",
      },
    },
  },
  {
    name: "supabase-dark",
    label: "Supabase Dark",
    tokens: {
      background: { default: "#1c1c1c", subtle: "#232323" },
      surface: {
        default: "#1c1c1c",
        raised: "#2e2e2e",
        overlay: "rgba(0,0,0,0.8)",
        floating: "#232323",
      },
      text: { primary: "#ededed", secondary: "#8b8b8b", disabled: "#4a4a4a", inverse: "#1c1c1c" },
      border: { default: "#2e2e2e", subtle: "#232323", strong: "#3e3e3e" },
      interactive: {
        primary: "#24b47e",
        primaryFg: "#ffffff",
        primaryHover: "#3ecf8e",
        primaryBg: "#1a3d2e",
        secondary: "#ededed",
        secondaryFg: "#1c1c1c",
        secondaryHover: "#d1d1d1",
        secondaryBg: "#2e2e2e",
        neutral: "#4a4a4a",
        neutralFg: "#ededed",
      },
    },
  },
  {
    name: "github-dark",
    label: "GitHub Dark",
    tokens: {
      background: { default: "#0d1117", subtle: "#161b22" },
      surface: {
        default: "#0d1117",
        raised: "#21262d",
        overlay: "rgba(0,0,0,0.8)",
        floating: "#161b22",
      },
      text: { primary: "#c9d1d9", secondary: "#8b949e", disabled: "#484f58", inverse: "#0d1117" },
      border: { default: "#30363d", subtle: "#21262d", strong: "#8b949e" },
      interactive: {
        primary: "#c9d1d9",
        primaryFg: "#0d1117",
        primaryHover: "#b1bac4",
        primaryBg: "#21262d",
        secondary: "#58a6ff",
        secondaryFg: "#ffffff",
        secondaryHover: "#388bfd",
        secondaryBg: "#1c3a5e",
        neutral: "#484f58",
        neutralFg: "#c9d1d9",
      },
    },
  },
  {
    name: "nord",
    label: "Nord",
    tokens: {
      background: { default: "#2e3440", subtle: "#3b4252" },
      surface: {
        default: "#2e3440",
        raised: "#434c5e",
        overlay: "rgba(0,0,0,0.6)",
        floating: "#3b4252",
      },
      text: { primary: "#eceff4", secondary: "#d8dee9", disabled: "#4c566a", inverse: "#2e3440" },
      border: { default: "#434c5e", subtle: "#3b4252", strong: "#4c566a" },
      interactive: {
        primary: "#d8dee9",
        primaryFg: "#2e3440",
        primaryHover: "#e5e9f0",
        primaryBg: "#434c5e",
        secondary: "#88c0d0",
        secondaryFg: "#2e3440",
        secondaryHover: "#8fbcbb",
        secondaryBg: "#3b4252",
        neutral: "#4c566a",
        neutralFg: "#eceff4",
      },
      status: {
        success: "#a3be8c",
        successBg: "#3b4252",
        warning: "#ebcb8b",
        warningBg: "#3b4252",
        danger: "#bf616a",
        dangerBg: "#3b4252",
        info: "#5e81ac",
        infoBg: "#3b4252",
      },
      focus: { ring: "#81a1c1" },
    },
  },
];
