// This file is auto-generated by scripts/generate-docs-manifest.ts
// Do not edit manually.

export const demoImports: Record<string, () => Promise<Record<string, unknown>>> = {
  "contact-01": () => import("@/components/blocks/contact-01/contact-01.demo"),
  "dashboard-01": () => import("@/components/blocks/dashboard-01/dashboard-01.demo"),
  "empty-state-01": () => import("@/components/blocks/empty-state-01/empty-state-01.demo"),
  "error-state-01": () => import("@/components/blocks/error-state-01/error-state-01.demo"),
  "faq-01": () => import("@/components/blocks/faq-01/faq-01.demo"),
  "forgot-password-01": () =>
    import("@/components/blocks/forgot-password-01/forgot-password-01.demo"),
  "hero-01": () => import("@/components/blocks/hero-01/hero-01.demo"),
  "loading-state-01": () => import("@/components/blocks/loading-state-01/loading-state-01.demo"),
  "login-01": () => import("@/components/blocks/login-01/login-01.demo"),
  "login-02": () => import("@/components/blocks/login-02/login-02.demo"),
  "pricing-01": () => import("@/components/blocks/pricing-01/pricing-01.demo"),
  "profile-01": () => import("@/components/blocks/profile-01/profile-01.demo"),
  "settings-01": () => import("@/components/blocks/settings-01/settings-01.demo"),
  "signup-01": () => import("@/components/blocks/signup-01/signup-01.demo"),
  "verify-email-01": () => import("@/components/blocks/verify-email-01/verify-email-01.demo"),
  badge: () => import("@blenx-dev/core/components/Badge/badge.demo"),
};
