import { createThemeContract } from "@vanilla-extract/css";

export const semanticVars = createThemeContract({
  background: {
    default: null,
    subtle: null,
  },
  surface: {
    default: null,
    raised: null,
    overlay: null,
    floating: null,
  },
  text: {
    primary: null,
    secondary: null,
    disabled: null,
    inverse: null,
  },
  border: {
    default: null,
    subtle: null,
    strong: null,
  },
  interactive: {
    primary: null,
    primaryFg: null,
    primaryHover: null,
    primaryBg: null,
    secondary: null,
    secondaryFg: null,
    secondaryHover: null,
    secondaryBg: null,
    neutral: null,
    neutralFg: null,
  },
  status: {
    success: null,
    successBg: null,
    warning: null,
    warningBg: null,
    danger: null,
    dangerBg: null,
    info: null,
    infoBg: null,
  },
  focus: {
    ring: null,
  },
  shadow: {
    sm: null,
    md: null,
    lg: null,
    xl: null,
  },
});

export const tokenVars = createThemeContract({
  font: {
    sans: null,
    body: null,
    mono: null,
  },
  fontSize: {
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
    xxxl: null,
    display: null,
    displayLg: null,
    hero: null,
  },
  fontWeight: {
    regular: null,
    medium: null,
    semibold: null,
    bold: null,
    extrabold: null,
  },
  lineHeight: {
    tight: null,
    snug: null,
    normal: null,
    relaxed: null,
    loose: null,
  },
  letterSpacing: {
    tight: null,
    snug: null,
    normal: null,
    wide: null,
    wider: null,
    widest: null,
  },
  spacing: {
    none: null,
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
    xxxl: null,
    huge: null,
    massive: null,
    titanic: null,
    "0": null,
    "0.5": null,
    "1": null,
    "2": null,
    "3": null,
    "4": null,
    "5": null,
    "6": null,
    "7": null,
    "8": null,
    "9": null,
    "10": null,
    "12": null,
    "16": null,
    "20": null,
    "24": null,
    "32": null,
    "40": null,
    "48": null,
  },
  borderRadius: {
    default: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
    full: null,
  },
  borderWidth: {
    hairline: null,
    thin: null,
    medium: null,
    thick: null,
    heavy: null,
  },
  duration: {
    instant: null,
    fast: null,
    normal: null,
    slow: null,
    slower: null,
    lazy: null,
  },
  easing: {
    linear: null,
    standard: null,
    enter: null,
    exit: null,
    spring: null,
    bounce: null,
  },
});
