import { createThemeContract } from "@vanilla-extract/css";

export const themeContract = createThemeContract({
  primary: "primary",
  primarySubtle: "primary-subtle",
  secondary: "secondary",
  primaryHover: "primary-hover",
  contentPrimary: "content-primary",
  contentSecondary: "content-secondary",
  contentDisabled: "content-disabled",
  contentAccent: "content-accent",
  contentOnPrimary: "content-on-primary",
  surface: "surface",
  surfaceSubtle: "surface-subtle",
  surfaceRaised: "surface-raised",
  surfaceHover: "surface-hover",
  surfaceOverlay: "surface-overlay",
  border: "border",
  borderSubtle: "border-subtle",
  borderStrong: "border-strong",
  borderRadius: "border-radius",
  background: "background",
  backgroundSubtle: "background-subtle",
  sentimentPositive: "sentiment-positive",
  sentimentPositiveSubtle: "sentiment-positive-subtle",
  sentimentPositiveHover: "sentiment-positive-hover",
  sentimentWarning: "sentiment-warning",
  sentimentWarningSubtle: "sentiment-warning-subtle",
  sentimentWarningHover: "sentiment-warning-hover",
  sentimentNegative: "sentiment-negative",
  sentimentNegativeSubtle: "sentiment-negative-subtle",
  sentimentNegativeHover: "sentiment-negative-hover",
  sentimentInfo: "sentiment-info",
  sentimentInfoSubtle: "sentiment-info-subtle",
  sentimentInfoHover: "sentiment-info-hover",
  focusRing: "focus-ring",
  shadowSm: "shadow-sm",
  shadowMd: "shadow-md",
  shadowLg: "shadow-lg",
  shadowXl: "shadow-xl",
  fontSize: "font-size",
  hoverOverlay: "hover-overlay",
  hoverOverlaySoft: "hover-overlay-soft",
});
export const tokenVars = createThemeContract({
  font: {
    sans: null,
    body: null,
    mono: null,
  },
  fontSize: {
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
    xxxl: null,
    display: null,
    displayLg: null,
    hero: null,
  },
  fontWeight: {
    regular: null,
    medium: null,
    semibold: null,
    bold: null,
    extrabold: null,
  },
  lineHeight: {
    tight: null,
    snug: null,
    normal: null,
    relaxed: null,
    loose: null,
  },
  letterSpacing: {
    tight: null,
    snug: null,
    normal: null,
    wide: null,
    wider: null,
    widest: null,
  },
  spacing: {
    none: null,
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
    xxxl: null,
    huge: null,
    massive: null,
    titanic: null,
    "0": null,
    "0.5": null,
    "1": null,
    "2": null,
    "3": null,
    "4": null,
    "5": null,
    "6": null,
    "7": null,
    "8": null,
    "9": null,
    "10": null,
    "12": null,
    "16": null,
    "20": null,
    "24": null,
    "32": null,
    "40": null,
    "48": null,
  },
  borderRadius: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
    full: null,
  },
  borderWidth: {
    hairline: null,
    thin: null,
    medium: null,
    thick: null,
    heavy: null,
  },
  duration: {
    instant: null,
    fast: null,
    normal: null,
    slow: null,
    slower: null,
    lazy: null,
  },
  easing: {
    linear: null,
    standard: null,
    enter: null,
    exit: null,
    spring: null,
    bounce: null,
  },
});
