import * as stylex from "@stylexjs/stylex";
import { theme } from "@blenx-dev/ui/lib/theme/contract.stylex";
import {
  borderRadius,
  borderWidth,
  fontSize,
  fontWeight,
  mediaQueries,
  spacing,
  zIndexVars,
} from "@blenx-dev/ui/lib/theme/tokens.stylex";

export const drawerStyles = stylex.create({
  swipeArea: {
    position: "fixed",
    zIndex: 50,
    touchAction: "none",
  },
  swipeAreaBottom: {
    left: 0,
    right: 0,
    bottom: 0,
    height: "32px",
  },
  swipeAreaTop: {
    left: 0,
    right: 0,
    top: 0,
    height: "32px",
  },
  swipeAreaLeft: {
    top: 0,
    bottom: 0,
    left: 0,
    width: "32px",
  },
  swipeAreaRight: {
    top: 0,
    bottom: 0,
    right: 0,
    width: "32px",
  },
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    backgroundColor: "rgba(0, 0, 0, 0.32)",
    backdropFilter: "blur(4px)",
    transitionProperty: {
      default: "opacity",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    transitionDuration: {
      default: "450ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: "cubic-bezier(0.32, 0.72, 0, 1)",
  },
  viewport: {
    position: "fixed",
    inset: 0,
    zIndex: zIndexVars.overlay,
    touchAction: "none",
    boxSizing: "border-box",
  },
  viewportBottom: {
    display: "grid",
    gridTemplateRows: "1fr auto",
    paddingTop: "48px",
  },
  viewportTop: {
    display: "grid",
    gridTemplateRows: "auto 1fr",
    paddingBottom: "48px",
  },
  viewportLeft: {
    display: "flex",
    justifyContent: "flex-start",
  },
  viewportRight: {
    display: "flex",
    justifyContent: "flex-end",
  },
  viewportInset: {
    paddingLeft: spacing.medium,
    paddingRight: spacing.medium,
  },
  popup: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    maxHeight: "100%",
    minHeight: 0,
    minWidth: 0,
    width: "100%",
    boxSizing: "border-box",
    backgroundColor: theme.surface,
    color: theme.contentPrimary,
    borderStyle: "solid",
    borderColor: theme.border,
    outline: "none",
    willChange: "transform",
    transitionProperty: {
      default: "transform, box-shadow, height, background-color, margin, padding",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    transitionDuration: {
      default: "450ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: "cubic-bezier(0.32, 0.72, 0, 1)",
  },
  popupDefault: {
    boxShadow: theme.shadowLg,
  },
  popupStraight: {
    "--stack-step": "0",
  },
  popupInset: {
    borderWidth: {
      default: "none",
      [mediaQueries.sm]: borderWidth.thin,
    },
    borderRadius: {
      default: "none",
      [mediaQueries.sm]: borderRadius.xlarge,
    },
  },
  popupBottom: {
    gridRowStart: 2,
    borderTopWidth: borderWidth.thin,
    borderTopLeftRadius: borderRadius.xlarge,
    borderTopRightRadius: borderRadius.xlarge,
  },
  popupTop: {
    borderBottomWidth: borderWidth.thin,
    borderBottomLeftRadius: borderRadius.xlarge,
    borderBottomRightRadius: borderRadius.xlarge,
  },
  popupLeft: {
    width: "calc(100% - 48px)",
    maxWidth: "28rem",
    borderRightWidth: borderWidth.thin,
    borderTopRightRadius: borderRadius.xlarge,
    borderBottomRightRadius: borderRadius.xlarge,
  },
  popupRight: {
    width: "calc(100% - 48px)",
    maxWidth: "28rem",
    borderLeftWidth: borderWidth.thin,
    borderTopLeftRadius: borderRadius.xlarge,
    borderBottomLeftRadius: borderRadius.xlarge,
  },
  closeButton: {
    position: "absolute",
    top: spacing.small,
    insetInlineEnd: spacing.small,
  },
  header: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.small,
    paddingTop: spacing.large,
    paddingLeft: spacing.large,
    paddingRight: spacing.large,
    boxSizing: "border-box",
  },
  footer: {
    display: "flex",
    flexDirection: {
      default: "column-reverse",
      [mediaQueries.sm]: "row",
    },
    gap: spacing.small,
    paddingLeft: spacing.large,
    paddingRight: spacing.large,
    boxSizing: "border-box",
    justifyContent: {
      [mediaQueries.sm]: "flex-end",
    },
  },
  footerDefault: {
    borderTopWidth: borderWidth.thin,
    borderTopStyle: "solid",
    borderTopColor: theme.borderSubtle,
    backgroundColor: theme.backgroundSubtle,
    paddingTop: spacing.medium,
    paddingBottom: spacing.medium,
  },
  footerBare: {
    paddingTop: spacing.medium,
    paddingBottom: spacing.large,
  },
  title: {
    fontSize: "20px",
    lineHeight: 1,
    fontWeight: fontWeight.semibold,
  },
  description: {
    fontSize: fontSize.small,
    lineHeight: 1.4,
    color: theme.contentSecondary,
  },
  panel: {
    boxSizing: "border-box",
    paddingTop: spacing.large,
    paddingLeft: spacing.large,
    paddingRight: spacing.large,
    paddingBottom: spacing.large,
  },
  bar: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.small,
    touchAction: "none",
  },
  barHorizontal: {
    insetInline: 0,
    height: "48px",
  },
  barVertical: {
    insetBlock: 0,
    width: "48px",
  },
  barTop: {
    bottom: 0,
  },
  barBottom: {
    top: 0,
  },
  barLeft: {
    right: 0,
  },
  barRight: {
    left: 0,
  },
  menu: {
    display: "flex",
    flexDirection: "column",
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: spacing.small,
    minHeight: "36px",
    paddingTop: spacing.xsmall,
    paddingBottom: spacing.xsmall,
    paddingLeft: spacing.small,
    paddingRight: spacing.small,
    borderRadius: borderRadius.small,
    border: "none",
    backgroundColor: "transparent",
    color: theme.contentPrimary,
    fontSize: fontSize.medium,
    textAlign: "left",
    cursor: "default",
    outline: "none",
  },
  menuItemDestructive: {
    color: theme.sentimentNegative,
  },
  separator: {
    height: "1px",
    backgroundColor: theme.borderSubtle,
    marginTop: spacing.xsmall,
    marginBottom: spacing.xsmall,
  },
  menuGroup: {
    display: "flex",
    flexDirection: "column",
  },
  menuGroupLabel: {
    paddingTop: spacing.xsmall,
    paddingBottom: spacing.xsmall,
    paddingLeft: spacing.small,
    paddingRight: spacing.small,
    fontSize: fontSize.xsmall,
    fontWeight: fontWeight.medium,
    color: theme.contentSecondary,
  },
  menuTrigger: {
    display: "flex",
    alignItems: "center",
    gap: spacing.small,
    minHeight: "36px",
    paddingTop: spacing.xsmall,
    paddingBottom: spacing.xsmall,
    paddingLeft: spacing.small,
    paddingRight: spacing.small,
    borderRadius: borderRadius.small,
    backgroundColor: "transparent",
    border: "none",
    color: theme.contentPrimary,
  },
  menuTriggerIcon: {
    marginLeft: "auto",
    marginRight: "-2px",
    opacity: 0.8,
  },
  menuCheckbox: {
    display: "grid",
    alignItems: "center",
    gap: spacing.small,
    minHeight: "36px",
    paddingTop: spacing.xsmall,
    paddingBottom: spacing.xsmall,
    paddingLeft: spacing.small,
    paddingRight: spacing.small,
    borderRadius: borderRadius.small,
    backgroundColor: "transparent",
    border: "none",
    color: theme.contentPrimary,
  },
  menuCheckboxDefault: {
    gridTemplateColumns: "1rem 1fr",
    paddingRight: spacing.medium,
  },
  menuCheckboxSwitch: {
    gridTemplateColumns: "1fr auto",
    paddingRight: spacing.xsmall,
  },
  menuCheckboxSwitchLabel: {
    gridColumnStart: 1,
  },
  menuCheckboxSwitchIndicator: {
    gridColumnStart: 2,
    display: "inline-flex",
    alignItems: "center",
    padding: "2px",
    borderRadius: borderRadius.full,
    backgroundColor: theme.borderSubtle,
  },
  menuCheckboxSwitchThumb: {
    width: "14px",
    height: "14px",
    borderRadius: borderRadius.full,
    backgroundColor: theme.background,
  },
  menuCheckboxIndicator: {
    gridColumnStart: 1,
  },
  menuCheckboxLabel: {
    gridColumnStart: 2,
  },
  menuRadio: {
    display: "grid",
    alignItems: "center",
    gap: spacing.small,
    minHeight: "36px",
    paddingTop: spacing.xsmall,
    paddingBottom: spacing.xsmall,
    paddingLeft: spacing.small,
    paddingRight: spacing.medium,
    borderRadius: borderRadius.small,
    backgroundColor: "transparent",
    border: "none",
    color: theme.contentPrimary,
    gridTemplateColumns: "1rem 1fr",
  },
  menuRadioIndicator: {
    gridColumnStart: 1,
  },
  menuRadioLabel: {
    gridColumnStart: 2,
  },
});
