import { recipe } from "@vanilla-extract/recipes";
import { semanticVars, tokenVars } from "@blenx-dev/theme/contract";

export const textVariants = recipe({
  base: {
    margin: 0,
    textDecoration: "none",
  },
  variants: {
    variant: {
      h1: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.displayLg,
        lineHeight: tokenVars.lineHeight.tight,
        fontWeight: tokenVars.fontWeight.bold,
        letterSpacing: tokenVars.letterSpacing.tight,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h2: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.xxl,
        lineHeight: tokenVars.lineHeight.tight,
        fontWeight: tokenVars.fontWeight.bold,
        letterSpacing: tokenVars.letterSpacing.tight,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h3: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.xl,
        lineHeight: tokenVars.lineHeight.snug,
        fontWeight: tokenVars.fontWeight.semibold,
        letterSpacing: tokenVars.letterSpacing.snug,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h4: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.lg,
        lineHeight: tokenVars.lineHeight.tight,
        fontWeight: tokenVars.fontWeight.semibold,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h5: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.md,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.semibold,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h6: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.sm,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.semibold,
        margin: 0,
        scrollMarginTop: "80px",
      },
      body1: {
        fontSize: tokenVars.fontSize.md,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.regular,
        margin: 0,
      },
      body2: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.sm,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.regular,
        margin: 0,
      },
      body3: {
        fontSize: tokenVars.fontSize.xs,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.regular,
        margin: 0,
      },
      body4: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.xxs,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.medium,
        letterSpacing: tokenVars.letterSpacing.wide,
        margin: 0,
      },
      caption: {
        fontFamily: tokenVars.font.body,
        fontSize: tokenVars.fontSize.xs,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.medium,
        letterSpacing: tokenVars.letterSpacing.wide,
        margin: 0,
      },
      creatorNote: {
        fontSize: tokenVars.fontSize.lg,
        lineHeight: "28px",
        fontWeight: tokenVars.fontWeight.regular,
        fontStyle: "italic",
        margin: 0,
      },
      p: {
        fontSize: tokenVars.fontSize.md,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.regular,
        margin: 0,
      },
      div: {
        fontSize: tokenVars.fontSize.md,
        lineHeight: tokenVars.lineHeight.normal,
        fontWeight: tokenVars.fontWeight.regular,
        margin: 0,
      },
      code: {
        margin: 0,
        backgroundColor: semanticVars.background.subtle,
        borderRadius: tokenVars.borderRadius.sm,
      },
    },
    textAlign: {
      left: { textAlign: "left" },
      center: { textAlign: "center" },
      right: { textAlign: "right" },
    },
    weight: {
      regular: { fontWeight: tokenVars.fontWeight.regular },
      medium: { fontWeight: tokenVars.fontWeight.medium },
      semibold: { fontWeight: tokenVars.fontWeight.semibold },
      bold: { fontWeight: tokenVars.fontWeight.bold },
    },
    transform: {
      uppercase: { textTransform: "uppercase" },
      capitalize: { textTransform: "capitalize" },
      none: { textTransform: "none" },
      lowercase: { textTransform: "lowercase" },
    },
    size: {
      xxs: { fontSize: tokenVars.spacing.xxs, lineHeight: tokenVars.lineHeight.tight },
      xs: { fontSize: tokenVars.spacing.xs, lineHeight: tokenVars.lineHeight.tight },
      sm: { fontSize: tokenVars.spacing.sm, lineHeight: tokenVars.lineHeight.tight },
      md: { fontSize: tokenVars.spacing.md, lineHeight: tokenVars.lineHeight.tight },
      lg: { fontSize: tokenVars.spacing.lg, lineHeight: tokenVars.lineHeight.tight },
      xl: { fontSize: tokenVars.spacing.xl, lineHeight: tokenVars.lineHeight.tight },
      xxl: { fontSize: tokenVars.spacing.xxl, lineHeight: tokenVars.lineHeight.tight },
      xxxl: { fontSize: tokenVars.spacing.xxxl, lineHeight: tokenVars.lineHeight.tight },
      huge: { fontSize: tokenVars.spacing.huge, lineHeight: tokenVars.lineHeight.tight },
      massive: { fontSize: tokenVars.spacing.massive, lineHeight: tokenVars.lineHeight.tight },
      titanic: { fontSize: tokenVars.spacing.titanic, lineHeight: tokenVars.lineHeight.tight },
    },
  },
});
