import { recipe } from "@vanilla-extract/recipes";
import { themeContract } from "@blenx-dev/theme/contract";
import {
  borderRadius,
  fonts,
  fontSize,
  fontWeight,
  letterSpacing,
  lineHeight,
  spacing,
} from "@blenx-dev/theme/tokens";

export const textVariants = recipe({
  base: {
    margin: 0,
    textDecoration: "none",
  },
  variants: {
    variant: {
      h1: {
        fontFamily: fonts.display,
        fontSize: fontSize.displayLg,
        lineHeight: lineHeight.tight,
        fontWeight: fontWeight.bold,
        letterSpacing: letterSpacing.tight,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h2: {
        fontFamily: fonts.heading,
        fontSize: fontSize.xxl,
        lineHeight: lineHeight.tight,
        fontWeight: fontWeight.bold,
        letterSpacing: letterSpacing.tight,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h3: {
        fontFamily: fonts.heading,
        fontSize: fontSize.xl,
        lineHeight: lineHeight.snug,
        fontWeight: fontWeight.semibold,
        letterSpacing: letterSpacing.snug,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h4: {
        fontFamily: fonts.heading,
        fontSize: fontSize.lg,
        lineHeight: lineHeight.tight,
        fontWeight: fontWeight.semibold,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h5: {
        fontFamily: fonts.heading,
        fontSize: fontSize.md,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.semibold,
        margin: 0,
        scrollMarginTop: "80px",
      },
      h6: {
        fontFamily: fonts.heading,
        fontSize: fontSize.sm,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.semibold,
        margin: 0,
        scrollMarginTop: "80px",
      },
      body1: {
        fontFamily: fonts.body,
        fontSize: fontSize.md,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.regular,
        margin: 0,
      },
      body2: {
        fontFamily: fonts.body,
        fontSize: fontSize.sm,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.regular,
        margin: 0,
      },
      body3: {
        fontFamily: fonts.body,
        fontSize: fontSize.xs,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.regular,
        margin: 0,
      },
      body4: {
        fontFamily: fonts.label,
        fontSize: fontSize.xxs,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.medium,
        letterSpacing: letterSpacing.wide,
        margin: 0,
      },
      caption: {
        fontFamily: fonts.label,
        fontSize: fontSize.xs,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.medium,
        letterSpacing: letterSpacing.wide,
        margin: 0,
      },
      creatorNote: {
        fontFamily: fonts.body,
        fontSize: fontSize.lg,
        lineHeight: "28px",
        fontWeight: fontWeight.regular,
        fontStyle: "italic",
        margin: 0,
      },
      p: {
        fontFamily: fonts.body,
        fontSize: fontSize.md,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.regular,
        margin: 0,
      },
      div: {
        fontFamily: fonts.body,
        fontSize: fontSize.md,
        lineHeight: lineHeight.normal,
        fontWeight: fontWeight.regular,
        margin: 0,
      },
      code: {
        margin: 0,
        backgroundColor: themeContract.backgroundSubtle,
        borderRadius: borderRadius.sm,
      },
    },
    textAlign: {
      left: { textAlign: "left" },
      center: { textAlign: "center" },
      right: { textAlign: "right" },
    },
    weight: {
      regular: { fontWeight: fontWeight.regular },
      medium: { fontWeight: fontWeight.medium },
      semibold: { fontWeight: fontWeight.semibold },
      bold: { fontWeight: fontWeight.bold },
    },
    transform: {
      uppercase: { textTransform: "uppercase" },
      capitalize: { textTransform: "capitalize" },
      none: { textTransform: "none" },
      lowercase: { textTransform: "lowercase" },
    },
    size: {
      xxs: { fontSize: spacing.xxs, lineHeight: lineHeight.tight },
      xs: { fontSize: spacing.xs, lineHeight: lineHeight.tight },
      sm: { fontSize: spacing.sm, lineHeight: lineHeight.tight },
      md: { fontSize: spacing.md, lineHeight: lineHeight.tight },
      lg: { fontSize: spacing.lg, lineHeight: lineHeight.tight },
      xl: { fontSize: spacing.xl, lineHeight: lineHeight.tight },
      xxl: { fontSize: spacing.xxl, lineHeight: lineHeight.tight },
      xxxl: { fontSize: spacing.xxxl, lineHeight: lineHeight.tight },
      huge: { fontSize: spacing.huge, lineHeight: lineHeight.tight },
      massive: { fontSize: spacing.massive, lineHeight: lineHeight.tight },
      titanic: { fontSize: spacing.titanic, lineHeight: lineHeight.tight },
    },
  },
});
