import { semanticVars, tokenVars } from "@blenx-dev/theme/contract";

export const spacing = {
  none: "0",
  xxs: tokenVars.spacing.xxs,
  xs: tokenVars.spacing.xs,
  sm: tokenVars.spacing.sm,
  md: tokenVars.spacing.md,
  lg: tokenVars.spacing.lg,
  xl: tokenVars.spacing.xl,
  huge: tokenVars.spacing.huge,
  xxl: tokenVars.spacing.xxl,
  xxxl: tokenVars.spacing.xxxl,
  massive: tokenVars.spacing.massive,
  "0": tokenVars.spacing["0"],
  "0.5": tokenVars.spacing["0.5"],
  "1": tokenVars.spacing["1"],
  "2": tokenVars.spacing["2"],
  "3": tokenVars.spacing["3"],
  "4": tokenVars.spacing["4"],
  "5": tokenVars.spacing["5"],
  "6": tokenVars.spacing["6"],
  "7": tokenVars.spacing["7"],
  "8": tokenVars.spacing["8"],
  "9": tokenVars.spacing["9"],
  "10": tokenVars.spacing["10"],
  "12": tokenVars.spacing["12"],
  "16": tokenVars.spacing["16"],
  "20": tokenVars.spacing["20"],
  "24": tokenVars.spacing["24"],
  "32": tokenVars.spacing["32"],
  "40": tokenVars.spacing["40"],
  "48": tokenVars.spacing["48"],
};

export const containerWidths = {
  xxs: "240px",
  xs: "320px",
  sm: "480px",
  md: "640px",
  lg: "768px",
  xl: "1024px",
  xxl: "1280px",
  xxxl: "1440px",
  480: "480px",
  640: "640px",
  400: "400px",
  560: "560px",
  full: "100%",
  screen: "100%",
  viewport: "90svw",
  maxViewport: "98svw",
};

export const colors = {
  primary: semanticVars.text.primary,
  default: "currentColor",
  transparent: "transparent",
  secondary: semanticVars.text.secondary,
  disabled: semanticVars.text.disabled,
  inverse: semanticVars.text.inverse,
  link: semanticVars.color.primary.default,
  error: semanticVars.color.danger.default,
  success: semanticVars.color.success.default,
  warning: semanticVars.color.warning.default,
  info: semanticVars.color.info.default,
} as const;
export const backgroundColors = {
  primary: semanticVars.color.primary.default,
  primaryHover: semanticVars.color.primary.hover,
  primaryActive: semanticVars.color.primary.active,
  secondary: semanticVars.color.secondary.default,
  secondaryHover: semanticVars.color.secondary.hover,
  secondaryActive: semanticVars.color.secondary.active,
  surface: semanticVars.surface.default,
  canvas: semanticVars.background.default,
  subtle: semanticVars.background.subtle,
  default: "inherit",
  transparent: "transparent",
  disabled: semanticVars.background.subtle,
  error: semanticVars.color.danger.bg,
  success: semanticVars.color.success.bg,
  warning: semanticVars.color.warning.bg,
  info: semanticVars.color.info.bg,
};
export const responsiveConditions = {
  base: {},
  sm: { "@media": "screen and (min-width: 640px)" },
  md: { "@media": "screen and (min-width: 768px)" },
  lg: { "@media": "screen and (min-width: 1280px)" },
  xl: { "@media": "screen and (min-width: 1536px)" },
} as const;
