// packages/core/iconify.config.ts

export default {
  collection: "lucide",
  icons: [
    "chevron-left",
    "chevron-right",
    "chevron-up",
    "chevron-down",
    "calendar",
    "square-check",
    "search",
    "check",
    "x",
    "plus",
    "minus",
    "copy",
    "list",
    "arrow-right",
    "bell",
    "chart-bar",
    "circle-alert",
    "ellipsis",
    "file-code",
    "folder-open",
    "info",
    "loader-circle",
    "map-pin",
    "palette",
    "play",
    "refresh-ccw",
    "send",
    "settings",
    "shopping-cart",
    "skull",
    "star",
    "trash-2",
    "user",
  ],
};
