import { CodeBlock } from "@/views/docs/mdx-components/CodeBlock";
import {
  AccordionItem,
  AccordionHeader,
  AccordionTrigger,
  AccordionPanel,
  Box,
  Text,
} from "@blenx-dev/core";

const semanticCode = `// Semantic tokens (what you edit)
export const theme = createThemeContract({
  primary: "",
  background: "",
  surface: "",
  // ...
});`;

const concreteCode = `// Concrete tokens (design primitives)
export const fontSize = {
  sm: "14px",
  md: "16px",
} as const;

export const spacing = {
  sm: "8px",
  md: "16px",
} as const;

export const borderRadius = {
  sm: "4px",
  md: "8px",
} as const;`;

const runtimeCode = `// Runtime theme (generated by Theme Builder)
export const customTheme = createTheme(theme, {
  primary: "#...",
  background: "#...",
});`;

export function HowItWorks() {
  return (
    <AccordionItem value="howitworks">
      <AccordionHeader>
        <AccordionTrigger>How It Works</AccordionTrigger>
      </AccordionHeader>
      <AccordionPanel>
        <Text variant="p">
          Blenx UI uses <Text variant="code">Vanilla Extract</Text> for its design system. Vanilla
          Extract compiles CSS at build time, enabling fast runtime performance with zero runtime
          CSS-in-JS overhead.
        </Text>
        <Text variant="p">
          <Text variant="body2" weight="bold">
            Semantic tokens
          </Text>{" "}
          (like <Text variant="code">primary</Text>, <Text variant="code">background</Text>) define
          the visual identity. These are declared with{" "}
          <Text variant="code">createThemeContract()</Text>:
        </Text>
        <Box paddingY="md">
          <CodeBlock code={semanticCode} />
        </Box>
        <Text variant="p">
          <Text variant="body2" weight="bold">
            Concrete tokens
          </Text>
          (like font sizes, spacing) are design primitives that stay consistent across themes:
        </Text>
        <Box paddingY="md">
          <CodeBlock code={concreteCode} />
        </Box>
        <Text variant="p">
          When you customize tokens in the Theme Builder, the preview wraps components in a{" "}
          <Text variant="code">div</Text> with inline CSS custom properties that override the
          semantic var values. This avoids <Text variant="code">createTheme()</Text> at runtime
          (which must be a static call per Vanilla Extract rules).
        </Text>
        <Text variant="p">
          To export your custom theme for use in your own project, use the Export panel to generate
          a static <Text variant="code">createTheme()</Text> call:
        </Text>
        <CodeBlock code={runtimeCode} />
      </AccordionPanel>
    </AccordionItem>
  );
}
