import { CodeBlock } from "@/views/docs/mdx-components/CodeBlock";
import { Accordion, Box, Text } from "@blenx-dev/components";

const semanticCode = `// Semantic tokens (what you edit)
export const theme = createThemeContract({
  primary: "",
  background: "",
  surface: "",
  // ...
});`;

const concreteCode = `// Concrete tokens (design primitives)
export const tokens = createThemeContract({
  fontSize: { small: "14px", medium: "16px" },
  spacing: { sm: "8px", md: "16px" },
  borderRadius: { sm: "4px", md: "8px" },
});`;

const runtimeCode = `// Runtime theme (generated by Theme Builder)
export const customTheme = createTheme(theme, {
  primary: "#...",
  background: "#...",
});`;

export function HowItWorks() {
  return (
    <Accordion.Item value="howitworks">
      <Accordion.Header>
        <Accordion.Trigger>How It Works</Accordion.Trigger>
      </Accordion.Header>
      <Accordion.Panel>
        <Text variant="p">
          Blenx UI uses <Text variant="code">Vanilla Extract</Text> for its design system. Vanilla
          Extract compiles CSS at build time, enabling fast runtime performance with zero runtime
          CSS-in-JS overhead.
        </Text>
        <Text variant="p">
          <Text variant="body2" weight="bold">
            Semantic tokens
          </Text>{" "}
          (like <Text variant="code">primary</Text>, <Text variant="code">background</Text>) define
          the visual identity. These are declared with{" "}
          <Text variant="code">createThemeContract()</Text>:
        </Text>
        <Box paddingY="medium">
          <CodeBlock code={semanticCode} />
        </Box>
        <Text variant="p">
          <Text variant="body2" weight="bold">
            Concrete tokens
          </Text>
          (like font sizes, spacing) are design primitives that stay consistent across themes:
        </Text>
        <Text variant="code">createThemeContract():</Text>
        <Box paddingY="medium">
          <CodeBlock code={concreteCode} />
        </Box>
        <Text variant="p">
          When you customize tokens in the Theme Builder, the preview wraps components in a{" "}
          <Text variant="code">div</Text> with inline CSS custom properties that override the
          semantic var values. This avoids <Text variant="code">createTheme()</Text> at runtime
          (which must be a static call per Vanilla Extract rules).
        </Text>
        <Text variant="p">
          To export your custom theme for use in your own project, use the Export panel to generate
          a static <Text variant="code">createTheme()</Text> call:
        </Text>
        <CodeBlock code={runtimeCode} />
      </Accordion.Panel>
    </Accordion.Item>
  );
}
