import * as stylex from "@stylexjs/stylex";
import { theme } from "@/lib/theme/contract.stylex";
import {
	borderWidth,
	fontSize,
	fontWeight,
	lineHeight,
	mediaQueries,
	spacing,
	zIndexVars,
} from "@/lib/theme/tokens.stylex";
export const alertDialogStyles = stylex.create({
	backdrop: {
		position: "fixed",
		inset: 0,
		zIndex: zIndexVars.overlay,
		backgroundColor: "rgba(0, 0, 0, 0.32)",
		backdropFilter: "blur(4px)",
		transitionProperty: "transform, opacity",
		transitionDuration: "200ms",
		opacity: {
			default: "1",
			"[data-ending-style]": 0,
			"[data-starting-style]": 0,
		},
	},
	viewport: {
		position: "fixed",
		inset: 0,
		zIndex: zIndexVars.modal,
		display: "grid",
		gridTemplateRows: "1fr auto 3fr",
		justifyItems: "center",
		padding: spacing.medium,
		boxSizing: "border-box",
	},
	popup: {
		position: "relative",
		gridRowStart: 2,
		display: "flex",
		flexDirection: "column",
		width: "100%",
		maxWidth: "28rem",
		minHeight: 0,
		transformOrigin: "center",
		borderWidth: borderWidth.thin,
		borderStyle: "solid",
		borderColor: theme.border,
		borderRadius: theme.borderRadius,
		backgroundColor: theme.surface,
		color: theme.contentPrimary,
		boxSizing: "border-box",
		opacity: "calc(1 - var(--nested-dialogs))",
		outline: "none",
		boxShadow: theme.shadowLg,
		transitionProperty: "opacity, translate",
		transitionDuration: "200ms",
		transitionTimingFunction: "ease-in-out",
		willChange: "transform",
		transform: {
			[mediaQueries.sm]: "scale(calc(1 - 0.1 * var(--nested-dialogs)))",
		},
		"::before": {
			content: '""',
			pointerEvents: "none",
			position: "absolute",
			inset: 0,
			borderRadius: "calc(16px - 1px)",
			boxShadow:
				"0 1px 0 rgba(0, 0, 0, 0.04), inset 0 0 0 1px rgba(255, 255, 255, 0.02)",
		},
		"[data-ending-style]": {
			opacity: 0,
			scale: 0.95,
		},
		"[data-starting-style]": {
			opacity: 0,
			scale: 0.95,
		},
	},
	closeButton: {
		position: "absolute",
		top: 4,
		right: 4,
	},
	header: {
		display: "flex",
		flexDirection: "column",
		gap: spacing.small,
		padding: spacing.large,
		boxSizing: "border-box",
		paddingBottom: spacing.small,
	},
	footer: {
		display: "flex",
		flexDirection: {
			default: "column-reverse",
			[mediaQueries.sm]: "row",
		},
		gap: spacing.small,
		paddingLeft: spacing.large,
		paddingRight: spacing.large,
		boxSizing: "border-box",
		justifyContent: {
			[mediaQueries.sm]: "flex-end",
		},
		borderBottomLeftRadius: { [mediaQueries.sm]: "calc(16px - 1px)" },
		borderBottomRightRadius: { [mediaQueries.sm]: "calc(16px - 1px)" },
	},
	footerDefault: {
		borderTopWidth: borderWidth.thin,
		borderTopStyle: "solid",
		borderTopColor: theme.borderSubtle,
		backgroundColor: theme.backgroundSubtle,
		paddingTop: spacing.medium,
		paddingBottom: spacing.medium,
	},
	footerBare: {
		paddingTop: spacing.medium,
		paddingBottom: spacing.large,
	},
	title: {
		fontSize: fontSize.large,
		lineHeight: lineHeight.tight,
		fontWeight: fontWeight.semibold,
		color: theme.contentPrimary,
	},
	description: {
		fontSize: fontSize.small,
		lineHeight: lineHeight.normal,
		color: theme.contentSecondary,
	},
	panel: {
		boxSizing: "border-box",
		padding: spacing.large,
		paddingTop: spacing.xsmall,
		paddingBottom: spacing.xsmall,
	},
	panelScrollFade: {
		opacity: 1,
	},
});
