import * as stylex from "@stylexjs/stylex";
import { theme } from "@/lib/theme/contract.stylex";
import { borderRadius, fontSize, spacing } from "@/lib/theme/tokens.stylex";

const styles = stylex.create({
	paragraph: {
		fontSize: fontSize.small,
		color: theme.contentSecondary,
		lineHeight: 1.6,
		marginBottom: spacing["2"],
	},
	codeBlock: {
		backgroundColor: theme.backgroundSubtle,
		borderRadius: borderRadius.small,
		padding: spacing["2"],
		fontFamily: '"DM Mono", monospace',
		fontSize: fontSize.xsmall,
		color: theme.contentPrimary,
		overflowX: "auto",
		whiteSpace: "pre",
		lineHeight: 1.5,
		marginBottom: spacing["2"],
	},
	inlineCode: {
		fontFamily: '"DM Mono", monospace',
		fontSize: fontSize.xsmall,
		backgroundColor: theme.backgroundSubtle,
		padding: "1px 4px",
		borderRadius: borderRadius.xsmall,
		color: theme.contentAccent,
	},
});

const semanticCode = `// Semantic tokens (what you edit)
export const theme = stylex.defineVars({
  primary: "#243142",
  background: "#F7F4EE",
  surface: "#FFFFFF",
  // ...
});`;

const concreteCode = `// Concrete tokens (design primitives)
export const tokens = stylex.defineVars({
  fontSize: { small: "14px", medium: "16px" },
  spacing: { sm: "8px", md: "16px" },
  borderRadius: { sm: "4px", md: "8px" },
});`;

const runtimeCode = `// Runtime theme (generated by Theme Builder)
export const customTheme = stylex.createTheme(theme, {
  primary: "#...",
  background: "#...",
});`;

export function HowItWorks() {
	return (
		<>
			<p {...stylex.props(styles.paragraph)}>
				Blenx UI uses <span {...stylex.props(styles.inlineCode)}>StyleX</span>{" "}
				for its design system. StyleX compiles CSS at build time, enabling fast
				runtime performance with zero runtime CSS-in-JS overhead.
			</p>
			<p {...stylex.props(styles.paragraph)}>
				<strong>Semantic tokens</strong> (like{" "}
				<span {...stylex.props(styles.inlineCode)}>primary</span>,{" "}
				<span {...stylex.props(styles.inlineCode)}>background</span>) define the
				visual identity. These are declared with{" "}
				<span {...stylex.props(styles.inlineCode)}>stylex.defineVars()</span>:
			</p>
			<pre {...stylex.props(styles.codeBlock)}>{semanticCode}</pre>
			<p {...stylex.props(styles.paragraph)}>
				<strong>Concrete tokens</strong> (like font sizes, spacing) are design
				primitives that stay consistent across themes:
			</p>
			<pre {...stylex.props(styles.codeBlock)}>{concreteCode}</pre>
			<p {...stylex.props(styles.paragraph)}>
				When you customize tokens in the Theme Builder, the preview wraps
				components in a <span {...stylex.props(styles.inlineCode)}>div</span>{" "}
				with inline CSS custom properties that override the semantic var values.
				This avoids{" "}
				<span {...stylex.props(styles.inlineCode)}>stylex.createTheme()</span>{" "}
				at runtime (which must be a static call per StyleX rules).
			</p>
			<p {...stylex.props(styles.paragraph)}>
				To export your custom theme for use in your own project, use the Export
				panel to generate a static{" "}
				<span {...stylex.props(styles.inlineCode)}>stylex.createTheme()</span>{" "}
				call:
			</p>
			<pre {...stylex.props(styles.codeBlock)}>{runtimeCode}</pre>
		</>
	);
}
