import { Accordion, Box, Text } from "@/components/ui";

const semanticCode = `// Semantic tokens (what you edit)
export const theme = stylex.defineVars({
  primary: "#243142",
  background: "#F7F4EE",
  surface: "#FFFFFF",
  // ...
});`;

const concreteCode = `// Concrete tokens (design primitives)
export const tokens = stylex.defineVars({
  fontSize: { small: "14px", medium: "16px" },
  spacing: { sm: "8px", md: "16px" },
  borderRadius: { sm: "4px", md: "8px" },
});`;

const runtimeCode = `// Runtime theme (generated by Theme Builder)
export const customTheme = stylex.createTheme(theme, {
  primary: "#...",
  background: "#...",
});`;

export function HowItWorks() {
	return (
		<Accordion.Item value="howitworks">
			<Accordion.Header>
				<Accordion.Trigger>How It Works</Accordion.Trigger>
			</Accordion.Header>
			<Accordion.Panel>
				<Text variant="p">
					Blenx UI uses{" "}
					<Text variant="code" color="accent">
						StyleX
					</Text>{" "}
					for its design system. StyleX compiles CSS at build time, enabling
					fast runtime performance with zero runtime CSS-in-JS overhead.
				</Text>
				<Text variant="p">
					<Text variant="body2" weight="bold">
						Semantic tokens
					</Text>{" "}
					(like{" "}
					<Text variant="code" color="accent">
						primary
					</Text>
					,{" "}
					<Text variant="code" color="accent">
						background
					</Text>
					) define the visual identity. These are declared with{" "}
					<Text variant="code" color="accent">
						stylex.defineVars()
					</Text>
					:
				</Text>
				<Box paddingY="medium">
					<Text variant="code">{semanticCode}</Text>
				</Box>
				<Text variant="p">
					<Text variant="body2" weight="bold">
						Concrete tokens
					</Text>
					(like font sizes, spacing) are design primitives that stay consistent
					across themes:
				</Text>
				<Text variant="code" color="accent">
					stylex.defineVars():
					<Box paddingY="medium">
						<Text variant="code">{concreteCode}</Text>
					</Box>
				</Text>
				<Text variant="p">
					When you customize tokens in the Theme Builder, the preview wraps
					components in a{" "}
					<Text variant="code" color="accent">
						div
					</Text>{" "}
					with inline CSS custom properties that override the semantic var
					values. This avoids{" "}
					<Text variant="code" color="accent">
						stylex.createTheme()
					</Text>{" "}
					at runtime (which must be a static call per StyleX rules).
				</Text>
				<Text variant="p">
					To export your custom theme for use in your own project, use the
					Export panel to generate a static{" "}
					<Text variant="code" color="accent">
						stylex.createTheme()
					</Text>{" "}
					call:
				</Text>
				<Text variant="code">{runtimeCode}</Text>
			</Accordion.Panel>
		</Accordion.Item>
	);
}
