/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeBuilderRouteImport } from './routes/theme-builder'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsThemingRouteImport } from './routes/docs/theming'
import { Route as DocsStylingRouteImport } from './routes/docs/styling'
import { Route as DocsPrimitivesRouteImport } from './routes/docs/primitives'
import { Route as DocsLimitationsRouteImport } from './routes/docs/limitations'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsDataTableRouteImport } from './routes/docs/data-table'
import { Route as DocsComponentsComponentRouteImport } from './routes/docs/components/$component'

const ThemeBuilderRoute = ThemeBuilderRouteImport.update({
  id: '/theme-builder',
  path: '/theme-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => DocsRoute,
} as any)
const DocsStylingRoute = DocsStylingRouteImport.update({
  id: '/styling',
  path: '/styling',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPrimitivesRoute = DocsPrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLimitationsRoute = DocsLimitationsRouteImport.update({
  id: '/limitations',
  path: '/limitations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDataTableRoute = DocsDataTableRouteImport.update({
  id: '/data-table',
  path: '/data-table',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsComponentRoute = DocsComponentsComponentRouteImport.update({
  id: '/components/$component',
  path: '/components/$component',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/theme-builder': typeof ThemeBuilderRoute
  '/docs/data-table': typeof DocsDataTableRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/$component': typeof DocsComponentsComponentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theme-builder': typeof ThemeBuilderRoute
  '/docs/data-table': typeof DocsDataTableRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs': typeof DocsIndexRoute
  '/docs/components/$component': typeof DocsComponentsComponentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/theme-builder': typeof ThemeBuilderRoute
  '/docs/data-table': typeof DocsDataTableRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/$component': typeof DocsComponentsComponentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/theme-builder'
    | '/docs/data-table'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/docs/'
    | '/docs/components/$component'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/theme-builder'
    | '/docs/data-table'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/docs'
    | '/docs/components/$component'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/theme-builder'
    | '/docs/data-table'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/docs/'
    | '/docs/components/$component'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  ThemeBuilderRoute: typeof ThemeBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-builder': {
      id: '/theme-builder'
      path: '/theme-builder'
      fullPath: '/theme-builder'
      preLoaderRoute: typeof ThemeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/styling': {
      id: '/docs/styling'
      path: '/styling'
      fullPath: '/docs/styling'
      preLoaderRoute: typeof DocsStylingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/primitives': {
      id: '/docs/primitives'
      path: '/primitives'
      fullPath: '/docs/primitives'
      preLoaderRoute: typeof DocsPrimitivesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/limitations': {
      id: '/docs/limitations'
      path: '/limitations'
      fullPath: '/docs/limitations'
      preLoaderRoute: typeof DocsLimitationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/data-table': {
      id: '/docs/data-table'
      path: '/data-table'
      fullPath: '/docs/data-table'
      preLoaderRoute: typeof DocsDataTableRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/$component': {
      id: '/docs/components/$component'
      path: '/components/$component'
      fullPath: '/docs/components/$component'
      preLoaderRoute: typeof DocsComponentsComponentRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsDataTableRoute: typeof DocsDataTableRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsLimitationsRoute: typeof DocsLimitationsRoute
  DocsPrimitivesRoute: typeof DocsPrimitivesRoute
  DocsStylingRoute: typeof DocsStylingRoute
  DocsThemingRoute: typeof DocsThemingRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentsComponentRoute: typeof DocsComponentsComponentRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDataTableRoute: DocsDataTableRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsLimitationsRoute: DocsLimitationsRoute,
  DocsPrimitivesRoute: DocsPrimitivesRoute,
  DocsStylingRoute: DocsStylingRoute,
  DocsThemingRoute: DocsThemingRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentsComponentRoute: DocsComponentsComponentRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  ThemeBuilderRoute: ThemeBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
