/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsThemingRouteImport } from './routes/docs/theming'
import { Route as DocsStylingRouteImport } from './routes/docs/styling'
import { Route as DocsPrimitivesRouteImport } from './routes/docs/primitives'
import { Route as DocsLimitationsRouteImport } from './routes/docs/limitations'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as ApiRSplatRouteImport } from './routes/api/r/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/docs/theming',
  path: '/docs/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStylingRoute = DocsStylingRouteImport.update({
  id: '/docs/styling',
  path: '/docs/styling',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPrimitivesRoute = DocsPrimitivesRouteImport.update({
  id: '/docs/primitives',
  path: '/docs/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLimitationsRoute = DocsLimitationsRouteImport.update({
  id: '/docs/limitations',
  path: '/docs/limitations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/docs/installation',
  path: '/docs/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRSplatRoute = ApiRSplatRouteImport.update({
  id: '/api/r/$',
  path: '/api/r/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/': typeof DocsIndexRoute
  '/api/r/$': typeof ApiRSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs': typeof DocsIndexRoute
  '/api/r/$': typeof ApiRSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs/': typeof DocsIndexRoute
  '/api/r/$': typeof ApiRSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/docs/'
    | '/api/r/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/docs'
    | '/api/r/$'
  id:
    | '__root__'
    | '/'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/docs/'
    | '/api/r/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsLimitationsRoute: typeof DocsLimitationsRoute
  DocsPrimitivesRoute: typeof DocsPrimitivesRoute
  DocsStylingRoute: typeof DocsStylingRoute
  DocsThemingRoute: typeof DocsThemingRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiRSplatRoute: typeof ApiRSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/docs/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/styling': {
      id: '/docs/styling'
      path: '/docs/styling'
      fullPath: '/docs/styling'
      preLoaderRoute: typeof DocsStylingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/primitives': {
      id: '/docs/primitives'
      path: '/docs/primitives'
      fullPath: '/docs/primitives'
      preLoaderRoute: typeof DocsPrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/limitations': {
      id: '/docs/limitations'
      path: '/docs/limitations'
      fullPath: '/docs/limitations'
      preLoaderRoute: typeof DocsLimitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/docs/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r/$': {
      id: '/api/r/$'
      path: '/api/r/$'
      fullPath: '/api/r/$'
      preLoaderRoute: typeof ApiRSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsLimitationsRoute: DocsLimitationsRoute,
  DocsPrimitivesRoute: DocsPrimitivesRoute,
  DocsStylingRoute: DocsStylingRoute,
  DocsThemingRoute: DocsThemingRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiRSplatRoute: ApiRSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
