import * as stylex from "@stylexjs/stylex";
import { theme } from "@blenx-dev/ui/lib/theme/contract.stylex";
import { borderRadius, fontSize, spacing } from "@blenx-dev/ui/lib/theme/tokens.stylex";

export const inputGroupStyles = stylex.create({
	group: {
		position: "relative",
		display: "inline-flex",
		width: "100%",
		minWidth: 0,
		alignItems: "center",
		borderRadius: borderRadius.large,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: theme.border,
		color: theme.contentPrimary,
		fontSize: fontSize.small,
		boxSizing: "border-box",
		minHeight: "40px",
		overflow: "hidden",
		transitionProperty: "border-color, box-shadow",
		transitionDuration: "150ms",
		":focus-within": {
			borderColor: theme.borderStrong,
			boxShadow: `0 0 0 2px ${theme.borderStrong}`,
		},
		":has([aria-invalid='true'])": {
			borderColor: theme.sentimentNegative,
		},
		":has([aria-invalid='true']:focus-visible)": {
			borderColor: theme.sentimentNegative,
			boxShadow: `0 0 0 2px ${theme.sentimentNegative}`,
		},
		":has(:disabled)": {
			opacity: 0.64,
			cursor: "not-allowed",
		},
		":has([data-align='block-start'], [data-align='block-end'])": {
			flexDirection: "column",
		},
	},
	addon: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		cursor: "text",
		flexShrink: 0,
		color: theme.contentSecondary,
		userSelect: "none",
		fontSize: fontSize.small,
		":has(:last-child[data-slot='badge'])": {
			marginInlineStart: 0,
		},
	},
	addonInlineStart: {
		paddingTop: "0px",
		paddingBottom: "0px",
		paddingLeft: "8px",
		paddingRight: "4px",
		alignSelf: "center",
	},
	addonInlineEnd: {
		order: 1,
		paddingLeft: "4px",
		paddingRight: "4px",
		alignSelf: "stretch",
		display: "flex",
		alignItems: "center",
	},
	addonBlockStart: {
		order: -1,
		width: "100%",
		justifyContent: "flex-start",
		paddingTop: "4px",
		paddingLeft: "4px",
		paddingRight: "4px",
	},
	addonBlockEnd: {
		order: 1,
		width: "100%",
		justifyContent: "flex-start",
		paddingBottom: "4px",
		paddingLeft: "4px",
		paddingRight: "4px",
	},
	text: {
		display: "flex",
		alignItems: "center",
		gap: spacing.small,
		whiteSpace: "nowrap",
		lineHeight: 1,
		color: theme.contentSecondary,
	},
	menu: {
		display: "flex",
		flexDirection: "column",
	},
	input: {
		flex: 1,
		minWidth: 0,
		width: "100%",
		height: "100%",
		border: "none",
		outline: "none",
		backgroundColor: "inherit",
		paddingTop: "8px",
		paddingBottom: "6px",
		paddingLeft: "8px",
		paddingRight: "8px",
		borderWidth: 0,
		fontSize: fontSize.small,
		color: theme.contentPrimary,
		"::placeholder": {
			color: theme.contentDisabled,
		},
		boxSizing: "border-box",
		lineHeight: 1.5,
		":disabled": {
			opacity: 0.5,
			cursor: "not-allowed",
		},
	},
	textarea: {
		flex: 1,
		minWidth: 0,
		width: "100%",
		border: "none",
		outline: "none",
		backgroundColor: "transparent",
		paddingTop: "8px",
		paddingBottom: "8px",
		borderWidth: 0,
		paddingLeft: "10px",
		paddingRight: "10px",
		fontSize: fontSize.small,
		color: theme.contentPrimary,
		resize: "none",
		"::placeholder": {
			color: theme.contentDisabled,
		},
	},
});
