import * as stylex from "@stylexjs/stylex";
import { theme } from "@/lib/theme/contract.stylex";
import { fontSize, fontWeight, spacing } from "@/lib/theme/tokens.stylex";

export const calendarStyles = stylex.create({
	root: {
		display: "inline-block",
		width: "100%",
	},
	months: {
		display: "flex",
		flexDirection: "column",
	},
	month: {},
	monthCaption: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		position: "relative",
		paddingBottom: spacing.small,
		minHeight: 40,
	},
	captionLabel: {
		fontSize: fontSize.medium,
		fontWeight: fontWeight.semibold,
		color: theme.contentPrimary,
		margin: 0,
		padding: 0,
	},
	nav: {
		height: "fit-content",
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
		position: "absolute",
		inset: 0,
		padding: spacing.xsmall,
		pointerEvents: "none",
		zIndex: 10,
	},
	buttonNav: {
		pointerEvents: "auto",
		appearance: "none",
		backgroundColor: "transparent",
		border: "none",
		padding: 0,
		font: "inherit",
		WebkitTapHighlightColor: "transparent",
		width: 28,
		height: 28,
		borderRadius: theme.borderRadius,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		color: theme.contentSecondary,
		cursor: "pointer",
		flexShrink: 0,
		":hover": {
			backgroundColor: theme.backgroundSubtle,
		},
		":focus-visible": {
			boxShadow: `0 0 0 2px ${theme.focusRing}`,
		},
	},
	chevron: {
		fill: "currentColor",
		width: 16,
		height: 16,
		display: "block",
	},
	monthGrid: {
		width: "100%",
		borderCollapse: "collapse",
	},
	weekday: {
		fontSize: fontSize.xsmall,
		fontWeight: fontWeight.medium,
		color: theme.contentSecondary,
		textAlign: "center",
		verticalAlign: "middle",
		padding: spacing.xxsmall,
		width: 40,
		height: 32,
		boxSizing: "border-box",
	},
	day: {
		textAlign: "center",
		verticalAlign: "middle",
		padding: 1,
		width: 40,
		height: 40,
		boxSizing: "border-box",
	},
	dayButton: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		width: "100%",
		height: "100%",
		minWidth: 32,
		minHeight: 32,
		maxWidth: 36,
		maxHeight: 36,
		borderRadius: theme.borderRadius,
		border: "none",
		backgroundColor: "transparent",
		cursor: "pointer",
		fontSize: fontSize.small,
		color: theme.contentPrimary,
		outline: "none",
		margin: "0 auto",
		padding: 0,
		fontFamily: "inherit",
		lineHeight: 1,
		transitionProperty: "background-color, color",
		transitionDuration: "100ms",
		transitionTimingFunction: "ease",
		":hover": {
			backgroundColor: theme.backgroundSubtle,
		},
		":focus-visible": {
			boxShadow: `0 0 0 2px ${theme.focusRing}`,
		},
	},
	dayButtonSelected: {
		backgroundColor: theme.primary,
		color: theme.contentOnPrimary,
		fontWeight: fontWeight.semibold,
		":hover": {
			backgroundColor: theme.primary,
		},
	},
	dayButtonToday: {
		fontWeight: fontWeight.semibold,
	},
	dayButtonDisabled: {
		color: theme.contentDisabled,
		cursor: "not-allowed",
		opacity: 0.5,
		":hover": {
			backgroundColor: "transparent",
		},
	},
	dayButtonOutside: {
		color: theme.contentDisabled,
		opacity: 0.5,
	},
	footer: {
		paddingTop: spacing.small,
	},
	dropdowns: {
		display: "flex",
		gap: spacing.xsmall,
		alignItems: "center",
	},
	dropdown: {
		appearance: "none",
		backgroundColor: theme.backgroundSubtle,
		border: `1px solid ${theme.border}`,
		borderRadius: theme.borderRadius,
		color: theme.contentPrimary,
		fontSize: fontSize.small,
		padding: `${spacing.xxsmall} ${spacing.small}`,
		cursor: "pointer",
		outline: "none",
		":focus-visible": {
			borderColor: theme.borderStrong,
			boxShadow: `0 0 0 2px ${theme.borderStrong}`,
		},
	},
});
