import * as stylex from "@stylexjs/stylex";
import { theme } from "@/lib/theme/contract.stylex";
import {
	borderRadius,
	duration,
	easing,
	fontSize,
	fontWeight,
	spacing,
} from "@/lib/theme/tokens.stylex";

export const tabsStyles = stylex.create({
	root: {
		display: "flex",
		flexDirection: "column",
		gap: spacing.medium,
		width: "100%",
		border: "none",
		backgroundColor: "transparent",
		padding: 0,
		borderRadius: 0,
		outline: "none",
	},
	rootVertical: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: spacing.large,
	},
	list: {
		position: "relative",
		display: "flex",
		overflow: "hidden",
		border: "none",
		outline: "none",
		backgroundColor: "transparent",
		padding: 0,
		borderRadius: 0,
	},
	listDefault: {
		flexDirection: "row",
		alignItems: "stretch",
		gap: 0,
		padding: 0,
		backgroundColor: "transparent",
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: theme.borderSubtle,
		borderRadius: 0,
	},
	listUnderline: {
		display: "flex",
		alignItems: "stretch",
		gap: spacing.large,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: theme.borderSubtle,
		padding: 0,
	},
	listUnderlineVertical: {
		flexDirection: "column",
		alignSelf: "auto",
		alignItems: "stretch",
		gap: 0,
		padding: 0,
		paddingRight: spacing.small,
		backgroundColor: "transparent",
		borderRightWidth: 1,
		borderRightStyle: "solid",
		borderRightColor: theme.borderSubtle,
		borderRadius: 0,
	},
	listVertical: {
		flexDirection: "column",
		alignItems: "stretch",
		minWidth: 220,
		borderRightWidth: 1,
		borderRightStyle: "solid",
		borderRightColor: theme.borderSubtle,
	},
	tabActiveVertical: {
		color: theme.contentPrimary,
		fontWeight: fontWeight.semibold,
		backgroundColor: theme.backgroundSubtle,
		borderRightWidth: 2,
		borderRightStyle: "solid",
		borderRightColor: theme.secondary,
	},
	tabUnderlineActive: {
		color: theme.contentPrimary,
		fontWeight: fontWeight.semibold,
		borderBottomWidth: 2,
		borderBottomStyle: "solid",
		borderBottomColor: theme.contentPrimary,
	},
	listGhost: {
		display: "flex",
		gap: spacing.small,
	},
	tabGhost: {
		padding: `${spacing.small} ${spacing.medium}`,
		borderRadius: borderRadius.medium,
		color: theme.contentSecondary,
		":hover": {
			backgroundColor: theme.backgroundSubtle,
		},
	},
	tabGhostActive: {
		backgroundColor: theme.backgroundSubtle,
		color: theme.contentPrimary,
		fontWeight: fontWeight.semibold,
	},
	listSegmented: {
		display: "flex",
		gap: spacing.xxsmall,
		padding: spacing.xxsmall,
		backgroundColor: theme.backgroundSubtle,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: theme.borderSubtle,
		borderRadius: borderRadius.large,
	},
	tabSegmented: {
		padding: `${spacing.small} ${spacing.medium}`,
		borderRadius: borderRadius.medium,
		color: theme.contentSecondary,
		":hover": {
			backgroundColor: theme.surface,
		},
	},
	tabSegmentedActive: {
		backgroundColor: theme.surface,
		color: theme.contentPrimary,
		fontWeight: fontWeight.semibold,
	},
	tab: {
		position: "relative",
		zIndex: 1,
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		gap: spacing.xsmall,
		minHeight: 36,
		backgroundColor: "transparent",
		cursor: "pointer",
		appearance: "none",
		outline: "none",
		borderWidth: 0,
		border: "none",
		textDecoration: "none",
		whiteSpace: "nowrap",
		userSelect: "none",
		font: "inherit",
		WebkitTapHighlightColor: "transparent",
		transition: `color ${duration.normal} ${easing.standard}, background-color ${duration.normal} ${easing.standard}, box-shadow ${duration.normal} ${easing.standard}`,
	},
	tabDefault: {
		position: "relative",
		padding: `${spacing.small} ${spacing.medium}`,
		borderRadius: 0,
		color: theme.contentSecondary,
		fontSize: fontSize.small,
		fontWeight: fontWeight.medium,
		lineHeight: 1.2,
		minHeight: 40,
		backgroundColor: "transparent",
		":hover": {
			color: theme.contentPrimary,
			backgroundColor: theme.backgroundSubtle,
		},
		":focus-visible": {
			boxShadow: `inset 0 -2px 0 ${theme.secondary}`,
		},
	},
	tabVertical: {
		width: "100%",
		justifyContent: "flex-start",
	},
	tabActive: {
		color: theme.contentPrimary,
		fontWeight: fontWeight.semibold,
	},
	tabDisabled: {
		opacity: 0.45,
		cursor: "not-allowed",
	},
	tabActiveDefault: {
		color: theme.contentPrimary,
		fontWeight: fontWeight.semibold,
		backgroundColor: "transparent",
		borderBottomWidth: 2,
		borderBottomStyle: "solid",
		borderBottomColor: theme.secondary,
	},
	tabUnderline: {
		padding: `${spacing.small} 0`,
		borderRadius: 0,
		color: theme.contentSecondary,
		fontSize: fontSize.small,
		fontWeight: fontWeight.medium,
		backgroundColor: "transparent",
		":hover": {
			color: theme.contentPrimary,
		},
	},
	indicator: {
		position: "absolute",
		pointerEvents: "none",
	},
	indicatorDefault: {
		display: "none",
	},
	indicatorUnderline: {
		zIndex: 0,
		borderRadius: borderRadius.full,
		backgroundColor: theme.secondary,
	},
	panel: {
		minWidth: 0,
		paddingTop: spacing.large,
		outline: "none",
	},
	panelVertical: {
		flex: 1,
	},
});
